# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentWord',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('freq', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'db_table': 'document_words',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='TfTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.IntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Package')),
            ],
            options={
                'db_table': 'tf_tables',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.AddField(
            model_name='documentword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Word'),
        ),
    ]
